/*****************************************************************************
*					File: INTCTRL_Program.h
*	 Description: contains functions definitions 
*								for Interrupt Control Module
*		Created By:	Kerolos Mikhail
*****************************************************************************/

/****************************************************************************
*					INCLUDES
****************************************************************************/
#include "INTCTRL_Interface.h"

/****************************************************************************
*					FUNCTIONS DEFINITIONS
****************************************************************************/
void IntCtrl_Init()
{
	
	/* Control Priority Grouping */
	APINT |= (0x05FA << VECTKEY);
	APINT |= (0x6 << PRIGROUP);					/* 2-Group, 4-Subgroup */
	 
	/* Control Interrupt Priority */ 
	#if (INTERRUPT_PERIPHERAL_GATES == 0)
							PRI0 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 1)
							PRI0 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 2)
							PRI0 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 3)
							PRI0 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 4)
							PRI1 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 5)
							PRI1 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 6)
							PRI1 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 7)
							PRI1 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 8)
							PRI2 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 9)
							PRI2 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 10)
							PRI2 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 11)
							PRI2 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 12)
							PRI3 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 13)
							PRI3 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 14)
							PRI3 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 15)
							PRI3 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 16)
							PRI4 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 17)
							PRI4 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 18)
							PRI4 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 19)
							PRI4 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 20)
							PRI5 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 21)
							PRI5 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 22)
							PRI5 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 23)
							PRI5 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 24)
							PRI6 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 25)
							PRI6 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 26)
							PRI6 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 27)
							PRI6 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 28)
							PRI7 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 29)
							PRI7 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 30)
							PRI7 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 31)
							PRI7 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 32)
							PRI8 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 33)
							PRI8 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 34)
							PRI8 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 35)
							PRI8 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 36)
							PRI9 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 37)
							PRI9 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 38)
							PRI9 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 39)
							PRI9 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 40)
							PRI10 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 41)
							PRI10 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 42)
							PRI10 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 43)
							PRI10 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 44)
							PRI11 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 45)
							PRI11 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 46)
							PRI11 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 47)
							PRI11 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 48)
							PRI12 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 49)
							PRI12 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 50)
							PRI12 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 51)
							PRI12 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 52)
							PRI13 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 53)
							PRI13 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 54)
							PRI13 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 55)
							PRI13 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 56)
							PRI14 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 57)
							PRI14 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 58)
							PRI14 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 59)
							PRI14 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 60)
							PRI15 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 61)
							PRI15 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 62)
							PRI15 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 63)
							PRI15 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 64)
							PRI16 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 65)
							PRI16 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 66)
							PRI16 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 67)
							PRI16 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 68)
							PRI17 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 69)
							PRI17 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 70)
							PRI17 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 71)
							PRI17 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 72)
							PRI18 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 73)
							PRI18 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 74)
							PRI18 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 75)
							PRI18 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 76)
							PRI19 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 77)
							PRI19 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 78)
							PRI19 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 79)
							PRI19 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 80)
							PRI20 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 81)
							PRI20 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 82)
							PRI20 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 83)
							PRI20 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 84)
							PRI21 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 85)
							PRI21 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 86)
							PRI21 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 87)
							PRI21 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 88)
							PRI22 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 89)
							PRI22 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 90)
							PRI22 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 91)
							PRI22 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 92)
							PRI23 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 93)
							PRI23 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 94)
							PRI23 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 95)
							PRI23 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 96)
							PRI24 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 97)
							PRI24 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 98)
							PRI24 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 99)
							PRI24 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 100)
							PRI25 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 101)
							PRI25 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 102)
							PRI25 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 103)
							PRI25 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 104)
							PRI26 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 105)
							PRI26 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 106)
							PRI26 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 107)
							PRI26 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 108)
							PRI27 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 109)
							PRI27 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 110)
							PRI27 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 111)
							PRI27 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 112)
							PRI28 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 113)
							PRI28 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 114)
							PRI28 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 115)
							PRI28 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 116)
							PRI29 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 117)
							PRI29 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 118)
							PRI29 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 119)
							PRI29 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 120)
							PRI30 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 121)
							PRI30 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 122)
							PRI30 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 123)
							PRI30 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 124)
							PRI31 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 125)
							PRI31 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 126)
							PRI31 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 127)
							PRI31 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 128)
							PRI32 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 129)
							PRI32 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 130)
							PRI32 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 131)
							PRI32 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 132)
							PRI33 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 133)
							PRI33 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 134)
							PRI33 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#elif (INTERRUPT_PERIPHERAL_GATES == 135)
							PRI33 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 24)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTD);
	#elif (INTERRUPT_PERIPHERAL_GATES == 136)
							PRI34 |= (INTERRUPT_GROUP_PRIORITY << GROUP_PRIORITY) | (INTERRUPT_SUB_GROUP_PRIORITY << INTA);
	#elif (INTERRUPT_PERIPHERAL_GATES == 137)
							PRI34 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 8)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTB);
	#elif (INTERRUPT_PERIPHERAL_GATES == 138)
							PRI34 |= (INTERRUPT_GROUP_PRIORITY << (GROUP_PRIORITY + 16)) | (INTERRUPT_SUB_GROUP_PRIORITY << INTC);
	#endif
	
	/* Enable NVIC Interrupt */
	if(INTERRUPT_PERIPHERAL_GATES < 32)
	{
		EN0 |= (1 << INTERRUPT_PERIPHERAL_GATES);
	}
	else if(INTERRUPT_PERIPHERAL_GATES < 64)
	{
		EN1 |= (1 << (INTERRUPT_PERIPHERAL_GATES - (32*1)));
	}
	else if(INTERRUPT_PERIPHERAL_GATES < 96)
	{
		EN2 |= (1 << (INTERRUPT_PERIPHERAL_GATES - (32*2)));
	}
	else if(INTERRUPT_PERIPHERAL_GATES < 128)
	{
		EN3 |= (1 << (INTERRUPT_PERIPHERAL_GATES - (32*3)));
	}
	else if(INTERRUPT_PERIPHERAL_GATES < 139)
	{
		EN4 |= (1 << (INTERRUPT_PERIPHERAL_GATES - (32*4)));
	}
	
}